# Generated by Django 4.2.28 on 2026-03-03 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alunos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aluno',
            name='email',
            field=models.CharField(default='', max_length=150),
        ),
    ]
